version: 2.1

orbs: 
  node: circleci/node@5.1.0

jobs:
  tests:
    parameters:
      node-ver:
        type: string
    docker:
      - image: cimg/node:<< parameters.node-ver >>-browsers
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-ver >>
      - restore_cache:
          keys:
            - v1-dep-<< parameters.node-ver >>-{{ checksum "package-lock.json" }}
      - node/install-packages:
          pkg-manager: npm
          cache-path: ~/project/node_modules
      - save_cache:
          paths:
            - node_modules
          key: v1-dep-<< parameters.node-ver >>-{{ checksum "package-lock.json" }}
      - run:
          command: npm run build --if-present
          name: Build app
      - run: 
          command: npm test
          name: Test app

workflows:
  js-tests:
    jobs:
      - tests:
          matrix:
            parameters:
              node-ver: ["16.5.0", "14.19.3"]
